nodejs/node-inspect

- examples/exceptions.js
- lib/internal/inspect-repl.js
- test/cli/exceptions.test.js
- test/cli/start-cli.js
Fixes https://github.com/buggerjs/node-inspect/issues/6
> `breakOn{Exception,Uncaught,None}`

- lib/internal/inspect-protocol.js
Fixes https://github.com/buggerjs/node-inspect/issues/11
> Use proper path for websocket

- lib/internal/inspect-repl.js
- lib/node-inspect.js
- test/cli/low-level.test.js
This allows user to directly access the protocol by exposing the agent proxies inside of the repl context. Because of the existing promise magic, things like the following "just work":
```
> ./cli.js examples/empty.js
debug> Debugger.getScriptSource({ scriptId: '64' })
{ scriptSource: '(function (exports, require, module, __filename, __dirname) { \n});' }
debug> _.scriptSource
'(function (exports, require, module, __filename, __dirname) { \n});'
```
> Support for low-level agent access

- lib/internal/inspect-protocol.js
- test/cli/profile.test.js
Fixes https://github.com/buggerjs/node-inspect/issues/10
> Handle big ws frames correctly

- .gitignore
- appveyor.yml
- lib/internal/inspect_repl.js
- package.json
- test/cli/backtrace.test.js
- test/cli/break.test.js
- test/cli/exceptions.test.js
- test/cli/launch.test.js
- test/cli/low-level.test.js
- test/cli/preserve-breaks.test.js
- test/cli/scripts.test.js
Making sure everything works on Windows.
> Run tests on windows

- lib/_inspect.js
This change makes inspect more compatible with the old debugger. There
are some Node.js core test-cases that are expecting the 'ok' to show up
here.
I am investigating if we can make `node debug` an alias of `node inspect`.
> print 'ok' after connection

- lib/internal/inspect_repl.js
This commits removes a commented-out `console.error()` statement.
> Remove console.error() statement

- lib/_inspect.js
Required for https://github.com/nodejs/node/pull/11441.
> Take --debug-port into account

- examples/alive.js
- examples/backtrace.js
- examples/cjs/index.js
- examples/cjs/other.js
- examples/exceptions.js
- examples/three-lines.js
- examples/use-strict.js
- lib/_inspect.js
- lib/internal/inspect_client.js
- lib/internal/inspect_repl.js
- test/cli/exceptions.test.js
- test/cli/launch.test.js
- test/cli/preserve-breaks.test.js
- test/cli/use-strict.test.js
Tested this by delaying the ready event by 250ms and going from there.
> Delay run until breakpoints are restored

- lib/internal/inspect_repl.js
* adds help text for profile and heap repl commands
> doc: add profile and heap to help

- package.json
- test/cli/backtrace.test.js
- test/cli/break.test.js
- test/cli/exceptions.test.js
- test/cli/exec.test.js
- test/cli/help.test.js
- test/cli/launch.test.js
- test/cli/low-level.test.js
- test/cli/preserve-breaks.test.js
- test/cli/profile.test.js
- test/cli/scripts.test.js
- test/cli/start-cli.js
- test/cli/use-strict.test.js
- test/cli/watchers.test.js
- test/node-inspect.test.js
The port export [no longer exists](https://github.com/nodejs/node-inspect/pull/26) and isn't in use. It was a hold-over from the old built-in debugger.
> Update test suite to pass on latest nightly

- lib/_inspect.js
- test/cli/launch.test.js
- test/cli/pid.test.js
Tested against https://github.com/nodejs/node/pull/11431.
On versions of node that don't use the new protocol by default, this test is skipped (and the feature will most likely not work).
> Support for debugging a pid

- lib/_inspect.js
Node 8.x no longer has --debug-brk and --inspect-brk is backwards
compatible with Node 7.
Ref: https://github.com/nodejs/node/pull/12197.
I will be cherry-picking this on https://github.com/nodejs/node/pull/11441.
> Prefer --inspect-brk over --debug-brk

- lib/_inspect.js
- lib/internal/inspect_client.js
- test/cli/launch.test.js
- test/cli/start-cli.js
Selecting port zero makes the inspector bind to a random port.
The inspector prints the URL it listens on to stderr.  Parse the
output from the child process to find the port number.
This commit coincidentally also makes `node inspect --port=0 x.js`
work and a regression test to that effect has been added.
Note that connecting to an existing process that listens on a
non-standard port with `node inspect -p <pid>` does not work
because then we never see the output from the inspector.
Fixes: https://github.com/nodejs/node/issues/16469
> fix: Make --inspect-port=0 work

- package.json
- test/cli/break.test.js
This gives us access to the `--output-file` option which makes it easier to integrate with CI test result reporting.
Also, for some reason there was a mismatch between the example line numbers and the breakpoint that the test tries to set. Added a fix that makes the test suite pass again consistently.
> Bump the tap version

- lib/internal/inspect_repl.js
- test/cli/heap-profiler.test.js
Fix a logic bug in `takeHeapSnapshot()` where it interpreted the item
count as the byte count, resulting in truncated snapshots.
This change hinges on the observation that the completion callback
always comes after any and all `'addHeapSnapshotChunk'` events.
I'm 95% sure after digging into the V8 inspector and its integration
with Node.js that the assumption above is correct.
If it turns out I'm mistaken, then we will most likely treat that as
a bug in Node.js, not node-inspect.
Fixes: https://github.com/nodejs/node-inspect/issues/56
> fix: Fix `takeHeapSnapshot()` truncation bug

- .npmrc
- lib/_inspect.js
- test/cli/invalid-args.test.js
Relatively simple solution that does a brand check on the error and suppresses the message.
> Handle blocked port

- .eslintrc
- CONTRIBUTING.md
- test/cli/invalid-args.test.js
* Enable async/await and other ES2017 features
* Add missing parenthesis around arrow param
> Fix eslint issues

- lib/_inspect.js
- lib/internal/inspect_repl.js
"REPLServer.rli" is deprecated and it's the reference of
the instance. So that we can replace the "repl.cli" with
"repl" to remove the deprecation warning in Node.js 12.
Refs: https://github.com/nodejs/node/pull/26260
> fix: replace the deprecated "repl.cli" with "repl"

- lib/internal/inspect_repl.js
- test/cli/break.test.js
- test/cli/exceptions.test.js
- test/cli/launch.test.js
- test/cli/low-level.test.js
- test/cli/preserve-breaks.test.js
- test/cli/scripts.test.js
- test/cli/start-cli.js
- test/cli/use-strict.test.js
To clean up the breakpoint matching, I pulled that regex into a dedicated helper in the test harness for launching the CLI.
> Address regressions due to changes in node

- lib/_inspect.js
- package.json
- test/cli/invalid-args.test.js
- test/cli/start-cli.js
Update ESLint and tap to quell warnings from `npm audit` and the
GitHub interface.
ESLint update required some changes to other files as indentation rules
are now more strictly enforced.
I'm seeing tests failing locally but that was the case before I updated
anything too, so hopefully this passes on Travis-CI or whatever.
> chore: Update dependencies

- .github/workflows/ci.yml
Add a workflow to run tests with GitHub Actions.
Based on the standard [Node.js starter workflow](https://github.com/actions/starter-workflows/blob/master/ci/node.js.yml) with the following changes:
- Add `pull_request` event so tests are run on pull requests
- Node.js 8.x removed
- Node.js 13.x added
- `fail-fast: false` so that all versions of Node.js are tested (without this as soon as one job fails the rest are canceled)
- `npm ci` replaced with `npm install` as this project doesn't have a `package-lock.json` or shrinkwrap file committed
Tests seem very broken with `tap` 14 so I've downgraded to `tap` 12 where tests pass on Node.js 12.x and 13.x but there are still failures on 10.x (hence this being WIP). Any help with fixing those failures would be appreciated as I'm not that …
> [WIP] chore: Test with GitHub Actions

- lib/internal/inspect_repl.js
This is deprecated and emits a warning with `--pending-deprecation`.
I’m afraid I’m not familiar enough with this code to provide a test,
unfortunately.
> fix: Avoid using process.binding()

- lib/_inspect.js
- lib/internal/inspect_repl.js
- test/cli/launch.test.js
- test/cli/start-cli.js
Fixes #65.
This PR is to automatically resume execution after debugger is paused on start, in case `NODE_INSPECT_RESUME_ON_START` environment variable is set to 1.
> feat: auto-resume on start breakpoint

- lib/_inspect.js
In windows, assigning a port may take a little longer than previously assumed value of 2000ms.
I am using Windows 10 1903 64bit, and it takes about 3000ms to initialize a port.
I increased the timeout to some higher value (9999ms) to give a little more space to Windows to initialize a port to use with the app.
This patch probably solves issues #48, #54 and #70
> "portIsFree" function's "timeout" parameter value increased to solve issues #48, #54 and #70

- package.json
tap@10 results in lots of audit warnings when running `npm install`.
tap@13 and above fails some tests as they currently exist.
Using tap@12 means no audit warnings on install and the tests still pass
without modification.
> chore: bump tap@10.7.0 to tap@12.7.0

- lib/internal/inspect_repl.js
- test/cli/exec.test.js
Node.js uses (or will use) _Ctrl+C_ with no spaces. To unify the
messages from inspect with other messages from the REPL and elsewhere,
make that change in node-inspect too.
> chore: align message with Node.js standard

- lib/internal/inspect_repl.js
The `{colors: true}` removed here is ignored by the function it is being
sent to.
> lib: remove unused function argument
